/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.llama.thrift;


import org.apache.thrift.TEnum;

public enum TLocationEnforcement implements org.apache.thrift.TEnum {
  MUST(0),
  PREFERRED(1),
  DONT_CARE(2);

  private final int value;

  private TLocationEnforcement(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TLocationEnforcement findByValue(int value) { 
    switch (value) {
      case 0:
        return MUST;
      case 1:
        return PREFERRED;
      case 2:
        return DONT_CARE;
      default:
        return null;
    }
  }
}
